### ISSUE TITLE
Failed test `tests::get_market_accounts`

### ISSUE THREAD

**Issue by aoikurokawa** [drift-labs/drift-rs#23]
When I run `cargo t tests::get_market_accounts`, the integration test fails.

The output is here.

```
---- tests::get_market_accounts stdout ----
thread 'tests::get_market_accounts' panicked at /home/aoi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bytemuck-1.15.0/src/internal.rs:32:3:
from_bytes>SizeMismatch
```

**Comment by wphan** [comment]
You are probably using an incompatible rust version, our cicd uses 1.62.0 (and use x86 rust if you are on an arm cpu), i think it should work up to 1.70.0

**Comment by aoikurokawa** [comment]
Thank you so much for quick response.
I changed 1.76.0, the test does not fail anymore.
