### ISSUE TITLE
Failed while creating DriftClient

### ISSUE THREAD

**Issue by Davones** [drift-labs/drift-rs#46]
When I create DriftClient, when I execute perp_market_map.sync() in the DriftClientBackend::new function, I get an error when decoding drift::state::perp_market::PerpMarket.
![drift-rs](https://github.com/user-attachments/assets/814b9b55-2a08-4305-8282-735f48e14618)

**Comment by jordy25519** [comment]
there are 2 common causes for this:

1) on M1 mac using the default 'aarch; target isn't supported, switch to an x86 target
2) using a rust version >1.76.0, switch to 1.760 exaclty

see: https://github.com/drift-labs/drift-rs?tab=readme-ov-file#mac-m-series

**Comment by jordy25519** [comment]
also if this happening on devnet, there's a known issue due to a recent upgrade that should be resolved soon

**Comment by Davones** [comment]
OS info: 
Linux version 5.15.0-105-generic (buildd@lcy02-amd64-054) (gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #115~20.04.1-Ubuntu SMP Mon Apr 15 17:33:04 UTC 2024

rust version:
rustc 1.79.0 (129f3b996 2024-06-10)

**Comment by jordy25519** [comment]
ok I think its your rust version `1.79.0` switch to `1.76.0`. tl;dr solana programs do some byte transmutation stuff that got broken after rust 1.76.0

**Comment by Davones** [comment]
problem solved, thanks for your help
