### ISSUE TITLE
devnet tx issues

### ISSUE THREAD

**Issue by jordy25519** [drift-labs/drift-rs#8]
latest devnet update causing some issues for landing txs, some variation of:
```
"Program log: AnchorError occurred. Error Code: PerpMarketNotFound. Error Number: 6078. Error Message: PerpMarketNotFound.",
```

while the same code/tx works on mainnet

**Comment by crispheaney** [comment]
this fixes it: https://github.com/drift-labs/protocol-v2/commit/cfbe238533dd28fc1421b3110b48cd9811985ae6
